export const BREADCRUMB_NAME_MAP: Record<string, string> = {
  products: "محصولات",
  "plant-doctor": "گیاه پزشک",
  blog: "مجله",
  styling: "چیدمان",
  care: "نگهداری",
  health: "آفت‌ها و بیماری‌ها",
  gift: "کادویی",
  decoration: "دکوراتیو",
  indoor: "آپارتمانی",
  contact: "تماس با ما",
  about: "درباره ما",
  cart: "سبد خرید",
  checkout: "تسویه حساب",
};
