import GeneralProvider from "@/components/providers/GeneralProvider";
import { getMeAction } from "@/features/auth/actions/me.actions";
import ScrollToTop from "@/lib/utils/ScrollToTop";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const modamFont = localFont({
  src: [
    {
      path: "../../public/static/fonts/Modam-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/static/fonts/Modam-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/static/fonts/Modam-Medium.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/static/fonts/Modam-SemiBold.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/static/fonts/Modam-Bold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/static/fonts/Modam-ExtraBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/static/fonts/Modam-Black.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-modam",
  display: "swap",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user: initialUser } = await getMeAction();
  return (
    <html
      lang="fa"
      dir="rtl"
      data-scroll-behavior="smooth"
      className={`${modamFont.variable} scroll-smooth`}
    >
      <body className="font-modam text-BLACK antialiased">
        <GeneralProvider initialUser={initialUser}>
          <div className="flex min-h-dvh flex-col justify-between">
            {children}
          </div>
        </GeneralProvider>
        <ScrollToTop />
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
