import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PublicHeader from "./components/layout/public/Public-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const modamFont = localFont({
  src: [
    {
      path: "./fonts/Modam-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Modam-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Modam-Medium.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Modam-SemiBold.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Modam-Bold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Modam-ExtraBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Modam-Black.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-modam",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={modamFont.variable}>
      <body className="container">
      <PublicHeader />
        {children}
        </body>
    </html>
  );
}
