import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ScrollToTop from "@/lib/utils/ScrollToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const modamFont = localFont({
  src: [
    {
      path: "../../public/fonts/Modam-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/Modam-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Modam-Medium.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Modam-SemiBold.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Modam-Bold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Modam-ExtraBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Modam-Black.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-modam",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`${modamFont.variable} scroll-smooth`}>
      <body className="font-modam antialiased text-BLACK">
        <div className="flex min-h-dvh flex-col justify-between">
          {children} 
        </div>
        <ScrollToTop />
      </body>
    </html>
  );
}
